// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qulsknbvlinjiuagolxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bHNrbmJ2bGluaml1YWdvbHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzAxODUsImV4cCI6MjA1ODIwNjE4NX0.iCQr28n1rR1FoEI3KMYWR4ROGnKwjxdWEbu9lZk-ODw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);